#!/bin/bash
# foucld.sh

set -euo pipefail

# This script is meant to be a wrapper around the foucl web application.
# Its role is to control the starting and stopping of the application, passing options to the server

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/foucld-usage"
. "$SCRIPT_DIR/foucld-start"
. "$SCRIPT_DIR/foucld-stop"

case "${1:-}" in

        start)
                shift
                foucld-start "$@"
                ;;

        stop)
                shift
                foucld-stop "$@"
                ;;
                
        restart)
                shift
                foucld-stop "$@" || true
                foucld-start "$@"
                ;;
        *)
                echo "Unknown command ${1:-}" >&2
                foucld-usage >&2
                exit 1
                ;;
esac
