#!/bin/bash
# foucld-usage.sh

foucld-usage() {
    cat <<EOF
USAGE: foucld [COMMAND] [OPTIONS]

Wrapper around the foucl web application. Its role is to control the starting and stopping of the application, passing options to the server

Options:
  -h    Displays this usage

Commands:
  start [--bin <path>] [--pidfile <path>] [--log-dir <path>]
  stop [--pidfile <path>]
  restart [--bin <path>] [--pidfile <path>] [--log-dir <path>]
EOF
}
